name: Deploy NestJS to server

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout source
      uses: actions/checkout@v4
        
    - name: Build Docker image
      run: docker build -t devops-project:${{ github.sha }} .

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Push Docker image
      run: |
        docker tag devops-project:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/devops-project:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/devops-project:latest
    
    - name: Deploy to server
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker rm -f nestjs
          docker rmi -f ${{ secrets.DOCKER_USERNAME }}/devops-project:latest
          docker pull ${{ secrets.DOCKER_USERNAME }}/devops-project:latest
          docker run -d \
            --name nestjs \
            --network backend-network \
            -e NODE_ENV=production \
            -e PORT=${{ secrets.PORT }} \
            -e POSTGRES_HOST=${{ secrets.POSTGRES_HOST }} \
            -e POSTGRES_PORT=${{ secrets.POSTGRES_PORT }} \
            -e POSTGRES_USER=${{ secrets.POSTGRES_USER }} \
            -e POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
            -e POSTGRES_DATABASE=${{ secrets.POSTGRES_DATABASE }} \
            -p 8000:8000 \
            ${{ secrets.DOCKER_USERNAME }}/devops-project:latest



